apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app: strapi
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
